function(obsfm_resolve_nuget_package package_name package_version url sha256 output_dir)
  set(_package_dir "${CMAKE_BINARY_DIR}/_deps/${package_name}-${package_version}")
  set(_archive "${CMAKE_BINARY_DIR}/_deps/${package_name}-${package_version}.nupkg")
  file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/_deps")

  if(NOT EXISTS "${_archive}")
    message(STATUS "Downloading ${package_name} ${package_version} from the official NuGet flat container")
    file(DOWNLOAD "${url}" "${_archive}.part" EXPECTED_HASH "SHA256=${sha256}" STATUS _download_status TLS_VERIFY ON)
    list(GET _download_status 0 _download_code)
    list(GET _download_status 1 _download_message)
    if(NOT _download_code EQUAL 0)
      file(REMOVE "${_archive}.part")
      message(FATAL_ERROR "Could not download ${package_name}: ${_download_message}. Set the corresponding package root to an already extracted, hash-verified NuGet package.")
    endif()
    file(RENAME "${_archive}.part" "${_archive}")
  endif()

  file(SHA256 "${_archive}" _actual_sha256)
  if(NOT _actual_sha256 STREQUAL "${sha256}")
    message(FATAL_ERROR "SHA-256 mismatch for ${_archive}: expected ${sha256}, got ${_actual_sha256}")
  endif()

  if(NOT EXISTS "${_package_dir}/.obsfm-extracted")
    file(REMOVE_RECURSE "${_package_dir}")
    file(MAKE_DIRECTORY "${_package_dir}")
    file(ARCHIVE_EXTRACT INPUT "${_archive}" DESTINATION "${_package_dir}")
    file(WRITE "${_package_dir}/.obsfm-extracted" "${sha256}\n")
  endif()

  set(${output_dir} "${_package_dir}" PARENT_SCOPE)
endfunction()
